spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/horror_alarm
    username: ryun
    password:
    driver-class-name: org.postgresql.Driver


  applicationname: 'horror-alarm-backend'
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true


  logging:
    level:
      org:
        hibernate:
          type: trace

